version: 2

multi-ecosystem-groups:
  infrastructure:
    schedule:
      interval: "weekly"
      day: "wednesday"
    open-pull-requests-limit: 25
    commit-message:
      prefix: "chore"
      include: "scope"

updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
    open-pull-requests-limit: 25
    cooldown:
      default-days: 7
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      - dependency-name: Microsoft.Extensions.Logging.Abstractions
        update-types:
          - version-update:semver-major
    groups:
      dotnet-minor-patch:
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"
      dotnet-major:
        update-types:
          - "major"
        patterns:
          - "*"


  - package-ecosystem: "github-actions"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: "infrastructure"
    cooldown:
      default-days: 7
