name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - beta
      - release/*
    tags:
      - v*
permissions: write-all
jobs:
  build:
    uses: LayeredCraft/devops-templates/.github/workflows/package-build.yaml@v6.2
    with:
      dotnet-version: |
        8.0.x
        9.0.x
        10.0.x
    secrets: inherit