name: PR Build

on:
  pull_request:
    branches:
      - main
permissions: write-all
jobs:
  build:
    uses: LayeredCraft/devops-templates/.github/workflows/pr-build.yaml@v4.0
    with:
      solution: LayeredCraft.StructuredLogging.sln
      hasTests: true
      dotnetVersion: |
        8.0.x
        9.0.x
      runCdk: false
    secrets: inherit