name: Publish Release

on:
  release:
    types: [published]

permissions: write-all

jobs:
  publish:
    uses: LayeredCraft/devops-templates/.github/workflows/publish-release.yml@main
    with:
      solution: LayeredCraft.StructuredLogging.slnx
      dotnetVersion: |
        8.0.x
        9.0.x
        10.0.x
        11.0.x
      hasTests: true
    secrets: inherit