name: Publish Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    uses: LayeredCraft/devops-templates/.github/workflows/publish-release.yml@v10.1
    with:
      solution: LayeredCraft.StructuredLogging.slnx
      dotnetVersion: |
        8.0.x
        9.0.x
        10.0.x
        11.0.x
      hasTests: true
    secrets: inherit

  push:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: LayeredCraft/devops-templates/.github/actions/nuget-push@v10.1
        with:
          nuget_user: ${{ secrets.NUGET_USER }}
